# ============================================================================
# CONFIGURAZIONE SORGENTI WIKI - DeepAiUG v1.4.1+
# ============================================================================
# Questo file configura le sorgenti documentali disponibili nell'interfaccia.
# Supporta: MediaWiki, DokuWiki, Cartella Locale
# 
# MODALITÀ DISPONIBILI:
# - fixed: Solo le sorgenti configurate, nessuna scelta utente
# - selectable: L'utente può scegliere tra le sorgenti configurate
# - custom: L'utente può anche aggiungere URL custom
#
# POSIZIONE FILE:
# - Stessa cartella di app.py
# - Oppure in ./config/wiki_sources.yaml
# ============================================================================

# Modalità di utilizzo
# Valori: "fixed" | "selectable" | "custom"
mode: "selectable"

# Sorgente predefinita (usata in modalità "fixed" o come default nelle altre)
default_source: "wikipedia_it"

# ============================================================================
# LISTA SORGENTI CONFIGURATE
# ============================================================================
# Ogni sorgente DEVE avere un campo "type" che specifica il tipo:
# - mediawiki: Wiki basate su MediaWiki (Wikipedia, ecc.)
# - dokuwiki: Wiki DokuWiki
# - local: Cartella locale con documenti
# ============================================================================

sources:
  # ========== MEDIAWIKI ==========
  
  wiki_associazione:
    type: "mediawiki"
    name: "Wiki Associazione"
    icon: "🌐"
    description: "Documentazione interna e procedure"
    url: "https://wiki.mia-associazione.it"
    api_path: "/w/api.php"
    requires_auth: false
    # username: "bot_user"
    # password: "bot_password"  # Meglio: WIKI_ASSOCIAZIONE_PASS
    namespaces:
      - 0      # Main (articoli)
    categories: []
    exclude_categories:
      - "Bozze"
      - "Da cancellare"
    exclude_pages:
      - "Pagina_principale"
      - "Sandbox"
    max_pages: 0  # 0 = tutte
    include_redirects: false
    timeout: 30
  
  wiki_locale:
    type: "mediawiki"
    name: "MediaWiki Locale (Test)"
    icon: "🖥️"
    description: "MediaWiki locale per sviluppo"
    url: "http://localhost:8080"
    api_path: "/api.php"
    requires_auth: false
    namespaces:
      - 0
    categories: []
    exclude_categories: []
    exclude_pages: []
    max_pages: 100
    include_redirects: false
    timeout: 10

  # ========== DOKUWIKI ==========
  
  docs_tecniche:
    type: "dokuwiki"
    name: "Documentazione Tecnica"
    icon: "📘"
    description: "Wiki DokuWiki per documentazione IT"
    url: "https://docs.example.com"
    # Autenticazione (opzionale)
    requires_auth: false
    # username: "reader"
    # password: "${DOKUWIKI_PASS}"
    # Namespace da includere (equivalente alle categorie)
    # Lasciare vuoto per tutti
    namespaces: []
    # Namespace da escludere
    exclude_namespaces:
      - "playground"
      - "wiki"
    # Pattern pagine da escludere (regex supportato)
    exclude_patterns:
      - "^start$"
      - "^sidebar$"
    # Limite pagine (0 = tutte)
    max_pages: 0
    timeout: 30
  
  dokuwiki_locale:
    type: "dokuwiki"
    name: "DokuWiki Locale"
    icon: "📗"
    description: "DokuWiki locale per test"
    url: "http://localhost:8081"
    requires_auth: false
    namespaces: []
    exclude_namespaces: []
    exclude_patterns: []
    max_pages: 50
    timeout: 10

  # ========== CARTELLA LOCALE ==========
  
  documenti_locali:
    type: "local"
    name: "Documenti Locali"
    icon: "📁"
    description: "File nella cartella documenti"
    folder_path: "/home/user/documenti"
    extensions:
      - ".md"
      - ".txt"
      - ".pdf"
    recursive: true
  
  # ========== WIKI PUBBLICHE DI TEST ==========

  wikipedia_it:
    type: "mediawiki"
    name: "Wikipedia IT (Test)"
    icon: "🌍"
    description: "Wiki di test - Categoria Intelligenza Artificiale"
    url: "https://it.wikipedia.org"
    api_path: "/w/api.php"
    requires_auth: false
    namespaces:
      - 0
    categories:
      - "Intelligenza artificiale"
    max_pages: 30
    include_redirects: false
    timeout: 30

  wikipedia_en:
    type: "mediawiki"
    name: "Wikipedia EN (Test)"
    icon: "🌎"
    description: "Test wiki - Artificial Intelligence category"
    url: "https://en.wikipedia.org"
    api_path: "/w/api.php"
    requires_auth: false
    namespaces:
      - 0
    categories:
      - "Artificial intelligence"
    max_pages: 20
    include_redirects: false
    timeout: 30

  wikivoyage_it:
    type: "mediawiki"
    name: "Wikivoyage IT"
    icon: "✈️"
    description: "Guide di viaggio - Destinazioni Italia"
    url: "https://it.wikivoyage.org"
    api_path: "/w/api.php"
    requires_auth: false
    namespaces:
      - 0
    categories:
      - "Italia"
    max_pages: 15
    include_redirects: false
    timeout: 30

  wikibooks_it:
    type: "mediawiki"
    name: "Wikibooks IT"
    icon: "📚"
    description: "Libri e manuali liberi - Informatica"
    url: "https://it.wikibooks.org"
    api_path: "/w/api.php"
    requires_auth: false
    namespaces:
      - 0
    categories:
      - "Informatica"
    max_pages: 20
    include_redirects: false
    timeout: 30

# ============================================================================
# IMPOSTAZIONI GLOBALI
# ============================================================================

global_settings:
  # User-Agent per le richieste API (importante per wiki pubbliche)
  user_agent: "DatapizzaBot/1.4.1 (https://github.com/EnzoGitHub27/datapizza-streamlit-interface)"
  
  # Ritardo tra richieste API (secondi) - per non sovraccaricare il server
  request_delay: 0.5
  
  # Dimensione batch per download pagine
  batch_size: 50
  
  # Directory per cache locale delle pagine
  cache_dir: "wiki_cache"
  
  # Tempo di vita cache (ore) - 0 = no cache
  cache_ttl_hours: 24
  
  # Formato export pagine prima dell'indicizzazione
  # Valori: "text" | "html" | "wikitext"
  export_format: "text"
  
  # Rimuovi markup wiki nel parsing
  strip_wiki_markup: true
  
  # Includi metadati pagina (autore, data modifica, etc.)
  include_metadata: true

# ============================================================================
# NOTE PER IL SISTEMISTA
# ============================================================================
# 
# 1. TIPI SUPPORTATI:
#    - mediawiki: Richiede `pip install mwclient`
#    - dokuwiki: Richiede `pip install dokuwiki`
#    - local: Nessuna dipendenza aggiuntiva
#
# 2. AUTENTICAZIONE:
#    Usa variabili ambiente per le password:
#    export WIKI_ASSOCIAZIONE_PASS="password"
#    Poi nel config: password: "${WIKI_ASSOCIAZIONE_PASS}"
#
# 3. NAMESPACE MEDIAWIKI:
#    0  = Main (articoli normali)
#    1  = Talk (discussioni)
#    2  = User (pagine utente)
#    4  = Project (namespace del progetto)
#    10 = Template
#    14 = Category
#
# 4. NAMESPACE DOKUWIKI:
#    I namespace DokuWiki sono gerarchici (es: "it:docs:manual")
#    Usa il nome senza prefisso (es: "docs" non "docs:")
#
# 5. ICONE DISPONIBILI:
#    🌐 🖥️ 📘 📗 📁 📄 📚 🏢 🔒 🌍
#
# 6. AGGIUNGERE NUOVI TIPI:
#    Per aggiungere supporto ad altri wiki (Confluence, BookStack, etc.):
#    1. Crea un adapter in rag/adapters/
#    2. Registralo in rag/adapters/__init__.py
#    3. Aggiungi il tipo in config/constants.py WIKI_TYPES
#    4. Aggiorna la UI in ui/sidebar/knowledge_base.py
#
# ============================================================================
